### ISSUE TITLE
Types 

### ISSUE THREAD

**Issue by reinzor** [tno-ivs/automotive_msgs#9]
Whats the difference between type_invalid and type_undecided?

**Comment by Heuvendw** [comment]
Regarding the LineSegment.msg file:

- Undecided indicates that it detects a line, however it has been determined what the line type is.

- Invalid marks that a line detection is not valid (ie no line available), and this measurement should be ignored.

**Comment by reinzor** [comment]
You mention regarding the LineSegment.msg but I do not see these comments in the message definitions.

**Comment by reinzor** [comment]
Closed by https://github.com/tno-ivs/automotive_msgs/pull/14
